### ISSUE TITLE
Failure to reconnect after monitor turned back on (connected via monitor USB)

### ISSUE THREAD

**Issue by rappo** [psieg/Lightpack#137]
I have my Pivos Vue Lightpack connected to my pc via my monitor's usb hub. This is handy because when I turn the monitor off (or it goes to sleep) the lights go off. Unfortunately it frequently fails to reconnect when it powers back up. I often have to close the app completely and reopen.

Anyone else have this issue?

On Windows 10. Happy to provide more info or help track down the cause if anyone has a lead.

**Comment by psieg** [comment]
Prismatik assumes the device remains connected throught the runtime of the program. If the device is back on when resuming from standby this works. In short, yes - working as intended.

You can plug the Lightpack into your PC and use the "keep lights on after suspend' option instead.

**Comment by rappo** [comment]
Thanks for the response.

In my use case I want the lights to go off when my monitor is turned off, which is why I have it plugged in to the monitor USB (and this also has the benefit of being cleaning for cable management, no extra cables running down to the PC). I want the lights to come back on when the monitor is turned back on.

Turning off works as expected, it's when I turn my monitor back on that Prismatik fails to reconnect... or if it does reconnect, it fails to set the lights to match the currently selected profile.

**Comment by psieg** [comment]
Do you turn off your monitor without putting the PC to standby? If not, just use the standby option and turn the monitor back on before the PC

**Comment by rappo** [comment]
I do turn my monitor off without putting the PC in standby. It stays active 24/7.

**Comment by psieg** [comment]
same as #84. will investigate next time i get around to working on Prismatik

**Comment by Neksteel** [comment]
Unfortunately, it doesn`t work for me, even with this new version. After reconnection of a device, I still have to close the app and reopen.

**Comment by psieg** [comment]
Well that is exactly what it should be doing.
Please set the log level to 1, restart Prismatik and then disconnect/reconnect.
Upload the log file somewhere so I can take a look.

**Comment by psieg** [comment]
sorry, my bad. the PR wasn't merged yet. Damn

**Comment by Neksteel** [comment]
Thanks for the reply.Here the log file.
[Prismatik.0.log](https://github.com/psieg/Lightpack/files/1832841/Prismatik.0.log)

**Comment by psieg** [comment]
Thanks, should be fixed with 5.11.2.15.

**Comment by Neksteel** [comment]
Still does not work when fully reconnected, thanks anyway)

**Comment by psieg** [comment]
That's weird. I'll need more details.
Can you please turn up the log level to level 2, restart prismatik, turn your screen off and on again after some time and then provide the log?

**Comment by Neksteel** [comment]
The log file:
[Prismatik.0.zip](https://github.com/psieg/Lightpack/files/1844382/Prismatik.0.zip)
There is a strange situation. Now, the lights remained with the last colors it had before unplugging a device. In short, they do not go off, yet they don`t receive any change in colors. An Arduino code is still the same.
