### ISSUE TITLE
Multiple Monitors Problem - waking blanked screens

### ISSUE THREAD

**Issue by cupnb** [psieg/Lightpack#140]
So I have configured prismatik to pick up my main monitor (It's a 21:9 1080p monitor). When prismatik is running and the screen blanks after the timeout it transfers some of the screen grabbing areas over to my second screen. This is kinda annoying because I always have to drag and drop them back in their position. Maybe you can do something about that.
Thanks in advance and keep up the great work ;)
Here's a screenshot:
![screenshot](https://user-images.githubusercontent.com/23528489/31516149-cbc05b24-af97-11e7-8044-0fbee1be0bb8.png)

**Comment by psieg** [comment]
When and why do you switch of the big screen but not the small one?

**Comment by cupnb** [comment]
Sry for not replying a long time. I don´t, this happens when Windows blanks the screen. The screens enter sleep mode. I wake them up by moving the mouse and this happens ^^

**Comment by Dawider10** [comment]
I've got similar problem but all the screen grabbing areas are moving and it happens only if I turn the monitor off manually.

**Comment by psieg** [comment]
And windows blanks only the big one?

**Comment by cupnb** [comment]
No, Windows blanks both screens. It only happpens if prismatik is running and in the screen grabbing mode. And ist always the same areas that get transferred.

**Comment by Domush** [comment]
I was just about to report the identical problem. My primary monitor is a 4k, so it takes longer than the secondary 1080p to refresh, and as a result, the above happens.

Is there a way to lock the capture zones, ignoring monitor sleep modes? For some weird reason only the exact capture sections above pictured get moved.

**Comment by Domush** [comment]
I think I've figured out what prompts this issue to happen, switching of the primary monitor. 

Since my secondary monitor is only 1080p, the capture area that is within the 1080p area gets stolen away from the 4k monitor, and when the 4k comes out of standby (and windows automatically switches it back to primary) the stolen capture area doesn't get switched back as it should.

Possible solutions: Setting an attribute to the capture areas which are monitor specific, rather than monitor # specific. Although I'm not sure why, if the capture areas follow the primary monitor once, they don't follow it a second time.

Thanks for a great app.

**Comment by psieg** [comment]
Good Info, thanks.
So it probably is the same as #84 and should be fixed by fixing that.

**Comment by cupnb** [comment]
OK, thank you so far ^^ The workaround should work and I´m sure you can fix the issue. If you need  further information let me know ;)

**Comment by Zaden722** [comment]
I have a very similar issue, but I have only noticed it happening when turning both or just my main display off and back on.
Display 1 1440p monitor on DP
Display 2 1080p tv on HDMI
When I turn the main display off, it transfers all the blocks to the secondary. When I turn it back on, it only pulls like 6 of the 10 back to the main display. It does the same thing when turning them off. When they come back up, the 10 blocks are split between the 2 displays again. Changing the order of how I turn them on and off does not seem to change anything.

**Comment by cupnb** [comment]
Hi, I'm back. My arduino wasn't working correctly for a long time but I have fixed that. So this problem is bugging me again. Even locking the .ini file doesen't seem to help since the program doesn't read the file after waking the screens (the wrong config seems to be stored in the RAM, it doesn't write the changes to the file.) You have to switch to another profile and back to make it work again which is very uncomfortable. Maybe you can do something about it?

**Comment by psieg** [comment]
Hi,

it is the next thing I will look at when I get back to doing something for this project.
I might have some free time in May, no promises though

**Comment by cupnb** [comment]
Sweet, thank you ^^ Really appreciate your work 👍

**Comment by psieg** [comment]
@cupnb can you verify this is fixed for you?

**Comment by cupnb** [comment]
The original problem seems to be fixed, but after I wake my displays no screen grabbing takes place. I´ll go through the open issues and open one if its not already there 👍

**Comment by psieg** [comment]
Is there something in the logs?

**Comment by PriviligedUser** [comment]
Sorry for reopening, but somehow original issue is not fixed for me, though I'm using the last version.
Here's the log: [prismatik.log](https://github.com/psieg/Lightpack/files/14545241/prismatik.log)

I can seen the line "Screen was resized or scaled, temporarily adjusting" there and then 73 zones are moved to another display.
